### ISSUE TITLE
block #2 doesnt make sense...

### ISSUE THREAD

**Issue by denistsoi** [dalinhuang99/dalinhuang99.github.io#3]
I've highlighted the dates in block 2.

Either the details of block 2 should go to block 3 or the dates in block 2 may be incorrect...

i.e. 

![screen shot 2017-11-02 at 3 36 04 pm](https://user-images.githubusercontent.com/3061779/32314581-9133d2f4-bfe3-11e7-8856-143d572ff173.png)

**Comment by dalindev** [comment]
ohhhh, you are right. It should be June 2016 - Nov 2016, I was Part-time at FarmLead and Full-time at i-Sight. Thanks! I will update the year and related hashes too... =D
