### ISSUE TITLE
问个问题

### ISSUE THREAD

**Issue by quentinyang** [dalinhuang99/dalinhuang99.github.io#8]
无意间看到你的github地址，考虑加入蚂蚁金服吗？
我这边是蚂蚁金服-财富事业群-无线平台-金融体验技术组的上海团队。有想法可随时联系我啊`wenjin.ywj@alibaba-inc.com`

**Comment by dalindev** [comment]
@quentinyang 十分感谢，将来有机会回国第一个投阿里

**Comment by quentinyang** [comment]
@dalinhuang99 好
